#ifndef _MRCANDEFS_H_
#define _MRCANDEFS_H_

#define ROSMSG_DRIVE 0
#define ROSMSG_STEERCURVE 1
#define ROSMSG_STEERPARA 2
#define ROSMSG_SPIN 3

#define COMMAND_DRIVE 0
#define COMMAND_STEERCURVE 1
#define COMMAND_STEERPARA 2
#define COMMAND_SPIN 3
#define COMMAND_SPINSTEER 4
#define COMMAND_CHANGESPEED 7
#define COMMAND_RELEASE 8
#define COMMAND_RESETALARM 9

#define COMMAND_INFO 35     //'S'
#define COMMAND_SETSMODE 38 //'V'
#define COMMAND_SETPMODE 40 //'X'
#define COMMAND_SDRIVE 49   //'a'
#define COMMAND_SSTOP 50    //'b'
#define COMMAND_SSPIN 66    //'r'

#endif
